// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK2izGcCSwQ4TVC3pY1q5ugPtJyC0FV14',
    appId: '1:657878967562:web:2b57ca4d56a5244cfb86f3',
    messagingSenderId: '657878967562',
    projectId: 'fir-fcm-learning',
    authDomain: 'fir-fcm-learning.firebaseapp.com',
    storageBucket: 'fir-fcm-learning.appspot.com',
    measurementId: 'G-LLNVPWZDB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Y8DLyxst0p4cZfrhnlmiBf1eCdXWYQQ',
    appId: '1:657878967562:android:86483914de7f64abfb86f3',
    messagingSenderId: '657878967562',
    projectId: 'fir-fcm-learning',
    storageBucket: 'fir-fcm-learning.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_-aKHtez003cOsrTUcNe_Q5nabf2chq8',
    appId: '1:657878967562:ios:8dd8cef764a9ae6afb86f3',
    messagingSenderId: '657878967562',
    projectId: 'fir-fcm-learning',
    storageBucket: 'fir-fcm-learning.appspot.com',
    iosClientId: '657878967562-47d8hu3hafq1kij88ip0m6u25ldrsgsk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_-aKHtez003cOsrTUcNe_Q5nabf2chq8',
    appId: '1:657878967562:ios:8dd8cef764a9ae6afb86f3',
    messagingSenderId: '657878967562',
    projectId: 'fir-fcm-learning',
    storageBucket: 'fir-fcm-learning.appspot.com',
    iosClientId: '657878967562-47d8hu3hafq1kij88ip0m6u25ldrsgsk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLearning',
  );
}
